apiVersion: apps/v1
kind: service
metadata:
  name: platformnpservice-srv
  spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
                  